config/routes.rb
Rails.application.routes.draw do
  root to: 'charts#index'
  post 'refresh', to: 'charts#refresh'
  get ':id', to: 'charts#edit', as: :edit
  patch ':id', to: 'charts#update', as: :update
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chart.rb
# == Schema Information
#
# Table name: charts
#
#  id              :integer          not null, primary key
#  songid          :integer
#  diff            :string
#  notes           :integer
#  title           :string
#  version         :integer
#  clear           :integer
#  score           :integer
#  miss            :integer
#  nc_level        :integer
#  hc_level        :integer
#  target_clear    :integer
#  target_priority :integer
#  description     :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  just_updated    :boolean
#  nc_gimmicks     :boolean
#  hc_gimmicks     :boolean
#

class Chart < ApplicationRecord
  enum clear: { 'white' => 0, 'gray' => 1, 'pink' => 2, 'green' => 3,
                'blue' => 4, 'red' => 5, 'yellow' => 6, 'teal' => 7 }
  enum target_clear: { 'NP' => 0, 'Fail' => 1, 'AC' => 2, 'EC' => 3,
                       'NC' => 4, 'HC' => 5, 'EXHC' => 6, 'FC' => 7 }
  enum target_priority: { 'low' => 1, 'mid' => 2, 'high' => 3 }
  enum diff: { '[a]' => 'spa', '[h]' => 'sph', '[n]' => 'spn' }

  require 'open-uri'
  @chart_link = 'http://json.iidx.me/donjar/sp/level/12/'
  @level_link = 'http://iidx.insane.pe.kr/json/musiclist/sp/level/12/'

  NC = '노멀'.freeze
  NC_GIMMICKS = '노멀 개인차'.freeze
  HC = '처리력'.freeze
  HC_GIMMICKS = '개인차'.freeze

  def to_s
    title + ' ' + diff
  end

  def self.populate_data
    chart_hash = JSON.load open(@chart_link)
    level_hash = JSON.load open(@level_link)
    chart_hash['musicdata'].each do |chart|
      c = Chart.find_by(songid: chart['data']['id'],
                        diff: chart['data']['diff']) || Chart.new
      level_data = level_hash['songs'].find do |s|
        s['songtitle'] == chart['data']['title']
      end
      update_from_data chart, level_data, c
    end

    remove_not_updated
  end

  def self.get_level(categories)
    if (desc = categories.find { |c| c.starts_with? NC })
      nc = desc.gsub("#{NC} ", '')
      nc_gimmicks = false
    end
    if (desc = categories.find { |c| c.starts_with? NC_GIMMICKS })
      nc = desc.gsub("#{NC_GIMMICKS} ", '')
      nc_gimmicks = true
    end

    if (desc = categories.find { |c| c.starts_with? HC })
      hc = desc.gsub("#{HC} ", '')
      hc_gimmicks = false
    elsif (desc = categories.find { |c| c.starts_with? HC_GIMMICKS })
      hc = desc.gsub("#{HC_GIMMICKS} ", '')
      hc_gimmicks = true
    end

    letter_to_number = { 'S+' => 10, 'S' => 9, 'A+' => 8, 'A' => 7, 'B+' => 6,
                         'B' => 5, 'C' => 4, 'D' => 3, 'E' => 2, 'F' => 1 }
    { nc: letter_to_number[nc], nc_gimmicks: nc_gimmicks,
      hc: letter_to_number[hc], hc_gimmicks: hc_gimmicks }
  end

  def self.update_from_data(song_data, level_data, chart_object)
    song = song_data['data']
    level = if level_data.nil?
              { nc: nil, hc: nil, nc_gimmicks: nil, hc_gimmicks: nil }
            else
              get_level level_data['categories']
            end
    chart_object.update(songid: song['id'], diff: song['diff'],
                        notes: song['notes'], title: song['title'],
                        version: song['version'], clear: song_data['clear'],
                        score: song_data['score'], miss: song_data['miss'],
                        nc_level: level[:nc], hc_level: level[:hc],
                        nc_gimmicks: level[:nc_gimmicks],
                        hc_gimmicks: level[:hc_gimmicks],
                        just_updated: true)
  end

  def self.remove_not_updated
    Chart.all.find_each do |chart|
      if chart.just_updated?
        chart.update(just_updated: false)
      else
        chart.destroy
      end
    end
  end

  def calc_rank
    return if score.nil?
    res = score
    inc = 2 * notes / 9
    rank = 0
    loop do
      res -= inc
      return format_rank(rank, (inc + res), res) if res < 0
      rank += 1
    end
  end

  def format_rank(rank, plus, minus)
    rank_array = %w(O F E D C B A AA AAA)
    curr_rank = rank_array[rank]
    next_rank = rank_array[rank + 1]
    "#{curr_rank}+#{plus} (#{next_rank}#{minus})"
  end

  def self.process_from_params(params)
    res = all
    res = res.where('version <= ?', params[:max_v]) if params[:max_v]
    res = res.where('clear <= ?', params[:max_clear]) if params[:max_clear]
    res = res.where('target_priority <= ?', params[:min_pr]) if params[:min_pr]
    res = res.order(params[:sort].to_s) if params[:sort]
    res = res.order('title')
    res = res.reverse if params[:sort_by] == 'descending'
    res
  end

  before_save do
    if target_clear && clear &&
       Chart.target_clears[target_clear] <= Chart.clears[clear]
      self.target_clear = nil
      self.target_priority = nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def index
    @charts = Chart.process_from_params(params)
  end

  def refresh
    Chart.populate_data
    redirect_to root_path
  end

  def edit
    @chart = Chart.find(params[:id])
  end

  def update
    Chart.find(params[:id]).update(chart_params)
    redirect_to root_path(request.GET)
  end

  private

  def chart_params
    params.require(:chart).permit(:description, :target_clear, :target_priority)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
  def bold(text)
    content_tag :b, text
  end

  def params_link(text, cls, **prms)
    link_to text, params.merge(prms).permit(:sort, :max_v, :max_clear,
                                            :min_pr, :sort_by),
            class: "btn #{cls}"
  end

  def priority_hash
    { '' => nil, 'Low' => 1, 'Mid' => 2, 'High' => 3 }
  end

  def all_params
    params.permit(:sort, :max_v, :max_clear, :min_pr, :sort_by)
  end
end

app/views/charts/edit.html.haml
.container
  %h1= @chart

  = form_for @chart, url: update_path(@chart, all_params) do |f|
    .row
      .col-sm-4
        %h2 Target Clear
        = f.select :target_clear, [nil] + Chart.target_clears.keys.to_a, {},
          class: 'form-control'

      .col-sm-4
        %h2 Target Priority
        = f.select :target_priority,
          [nil] + Chart.target_priorities.keys.to_a, {}, class: 'form-control'

      .col-sm-4
        %h2 Notes
        = f.text_field :description, class: 'form-control'

    = f.submit 'Submit', class: 'btn btn-default', id: 'edit-submit'

app/views/charts/index.html.haml
.container
  = link_to 'Refresh', refresh_path, method: :post, class: 'btn btn-default'
  = link_to 'Reset', root_path, class: 'btn btn-default'

  %div
    %h1 Filter
    = params_link '<= RA', 'btn-success', max_v: 18
    = params_link '<= Lin', 'btn-success', max_v: 19
    = params_link '<= tri', 'btn-success', max_v: 20
    = params_link '<= SPA', 'btn-success', max_v: 21
    = params_link '<= PEN', 'btn-success', max_v: 22
    = params_link '<= cop', 'btn-success', max_v: 23

    = params_link '< HC', 'btn-warning', max_clear: 4
    = params_link '< NC', 'btn-warning', max_clear: 3
    = params_link '< EC', 'btn-warning', max_clear: 2

    = params_link 'Low Priority', 'btn-info', min_pr: 1
    = params_link 'Med Priority', 'btn-info', min_pr: 2
    = params_link 'High Priority', 'btn-info', min_pr: 3

  %div
    %h1 Sort
    = params_link 'Alphabet', 'btn-danger', sort: 'title'
    = params_link 'NC level', 'btn-danger', sort: 'nc_level'
    = params_link 'HC level', 'btn-danger', sort: 'hc_level'
    = params_link 'Notes', 'btn-danger', sort: 'notes'
    = params_link 'Clear', 'btn-danger', sort: 'clear'
    = params_link 'Priority', 'btn-danger', sort: 'target_priority'
    = params_link 'Miss Count', 'btn-danger', sort: 'miss'

    = params_link 'ASC', 'btn-primary', sort_by: 'ascending'
    = params_link 'DESC', 'btn-primary', sort_by: 'descending'

  %table.table.table-condensed.table-responsive.table-striped
    %thead
      %tr
        %th Clear
        %th Notes
        %th Version
        %th Title
        %th NC
        %th HC
        %th Target
        %th Priority
        %th Desc
        %th Score
        %th Miss Count
    %tbody
      - @charts.each do |chart|
        %tr
          %td{ style: "background-color: #{chart.clear}" }
          %td= chart.notes
          %td= chart.version
          %td= link_to chart, edit_path(chart, all_params)
          %td= chart.nc_gimmicks ? bold(chart.nc_level) : chart.nc_level
          %td= chart.hc_gimmicks ? bold(chart.hc_level) : chart.hc_level
          %td= chart.target_clear
          %td= chart.target_priority
          %td= chart.description
          %td= chart.calc_rank
          %td= chart.miss

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title IIDX Level 12 Stats
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all',
      'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application',
      'data-turbolinks-track': 'reload'
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1' }
  %body= yield